### ISSUE TITLE
Conteggio dei giorni totali sbagliato

### ISSUE THREAD

**Issue by Halolegend94** [massicode/giacenzamedia-n26#1]
Ciao,

come end date a riga 37,
```ed1 = str(datetime.datetime.now().year - 1) + '-12-31'```

dovresti usare invece
```ed1 = str(datetime.datetime.now().year ) + '-1-1'```

perchè quando vai a contare i giorni  rimanenti facendo la sottrazione tra date
```
d1 = datetime.datetime.strptime(initialDate, '%Y-%m-%d')
d2 = datetime.datetime.strptime(endDate, '%Y-%m-%d')  
days = (d2 - d1).days
```
non stai considerando l'ultimo giorno (l'estremo è escluso in pratica)
Infatti eseguendo il programma dice che hai diviso per 364.

**Comment by massicode** [comment]
Ciao,
grazie per la segnalazione, l'ho sistemato.
